#!/usr/bin/env bash

# Shows the output of every command
set +x

activateHM() {
  HOME_MANAGER_BACKUP_EXT=bak result/activate
}

rebuild_home() {
  nix build .#homeConfigurations.adamz.activationPackage && activateHM
}

rebuild_system() {
  sudo nixos-rebuild switch --flake .#asus-tuf 
}

case $1 in
  "home")
    rebuild_home;;
  "system")
    rebuild_system;;
  "all")
    rebuild_system && rebuild_home;;
  *)
    echo "expected 'home' 'system' or 'all'";;
esac
